# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "anatomia" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "0553f252d04e3ad2af1c677e0eb8d5d591e25840f8061e8ceac321baedaa549d"
      url "https://github.com/yeisme/yeisme-dist/releases/download/anatomia/v#{version}/anatomia_#{version}_Darwin_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "406abef0dbec91fdf0734e5858f28eec90a7fd60bfdf04a9f221c024012f4041"
      url "https://github.com/yeisme/yeisme-dist/releases/download/anatomia/v#{version}/anatomia_#{version}_Darwin_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  on_linux do
    on_arm do
      sha256 "2af1f3c72dcc40233d969246023aace3be9d1d5056306e5c3eab3f98e39ecbd0"
      url "https://github.com/yeisme/yeisme-dist/releases/download/anatomia/v#{version}/anatomia_#{version}_Linux_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "e2ba699e9f2155a76de06d1f684ee1740033cb7492795d4ebbe5f6b0a7bb49b5"
      url "https://github.com/yeisme/yeisme-dist/releases/download/anatomia/v#{version}/anatomia_#{version}_Linux_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "anatomia"
  desc "Authorized video analysis and evidence workflow CLI"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the yeisme-dist catalog."
  end

  binary "anatomia"

  # No zap stanza required
end
