# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "credentialctl" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "353c660ef4a8bab4a029a451b29ed79d97973a212fd6f226d04f9ddc4ae1dd76"
      url "https://github.com/yeisme/yeisme-dist/releases/download/credentialctl/v#{version}/credentialctl_#{version}_darwin_aarch64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "14a40f8a4b7e3cd4d8706afd6b1835ab4a0be4f03400cc63441e961fe8571f9d"
      url "https://github.com/yeisme/yeisme-dist/releases/download/credentialctl/v#{version}/credentialctl_#{version}_darwin_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  on_linux do
    on_arm do
      sha256 "f871e10f7fcb35c75e19287c8d86b47ad0652f29a77bf458ae388626f184fdb5"
      url "https://github.com/yeisme/yeisme-dist/releases/download/credentialctl/v#{version}/credentialctl_#{version}_linux_aarch64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "ee856a76a33a31ad36d5829448e8115972bf92196a9709c72ed8678e890e0feb"
      url "https://github.com/yeisme/yeisme-dist/releases/download/credentialctl/v#{version}/credentialctl_#{version}_linux_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "credentialctl"
  desc "Local shared credential and project-secret CLI"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the yeisme-dist catalog."
  end

  binary "credentialctl"

  caveats <<~EOS
    Install or update the credentialctl Agent Skill:
      npx --yes skills add https://github.com/yeisme/yeisme-agent-my-skills --skill credentialctl-usage --yes
  EOS

  # No zap stanza required
end
