# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "eikona" do
  version "0.7.5"

  on_macos do
    on_arm do
      sha256 "c76f16e8903a2ca522535293b82880fea932122899a513ec198c38c4fe66f76d"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Darwin_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "1eb40154b7b1c18aec8ef58ca40ab7b9bc3512d2b3d86b3d0dce3c05ad167472"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Darwin_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end
  on_linux do
    on_arm do
      sha256 "c48e9ffe14f489deba55c9eacff44a2727cdf5f7f49abd24f47acb9ba66202a2"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Linux_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "3ca4809ca95da5c1e9e6b0e1d7b1543e05f7ef4e016be22cfb402f762af826e7"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Linux_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "eikona"
  desc "Agent-first visual asset runtime and image-generation CLI"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the verified yeisme-dist catalog."
  end

  binary "eikona"

  caveats <<~EOS
    Preview local configuration and exact-version Agent Skills setup:
      eikona setup
    Apply the reviewed local setup:
      eikona setup --yes
  EOS

  # No zap stanza required
end
