# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "scaena" do
  version "0.2.1"

  on_linux do
    on_intel do
      sha256 "db5ff3f54c168614adaac2152b704263093428cacb81d03cf0a0bdc6c074072a"
      url "https://github.com/yeisme/yeisme-dist/releases/download/scaena/v0.2.1/scaena_linux_amd64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "scaena"
  desc "Short-drama production CLI and backend"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the verified yeisme-dist catalog."
  end

  binary "scaena"

  # No zap stanza required
end
