# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "sonora" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "6c1404486b1d4d14a42af1db9180c03a25986aa319a0bf99d93e70e6296b7036"
      url "https://github.com/yeisme/yeisme-dist/releases/download/sonora/v0.2.0/sonora_0.2.0_Darwin_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "8abf00873a306b48d51397b4a85cef725d621bc47b4bc27c1855eb5e09914a8c"
      url "https://github.com/yeisme/yeisme-dist/releases/download/sonora/v0.2.0/sonora_0.2.0_Darwin_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7daf21415e6818be9ff67e93f71581e727cca7074b7fa9214ef3ba6d3e64e2e"
      url "https://github.com/yeisme/yeisme-dist/releases/download/sonora/v0.2.0/sonora_0.2.0_Linux_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "8ab2c307e561327a1a04b089edefe1cdaffb23db252000b26ef264ad06a64db4"
      url "https://github.com/yeisme/yeisme-dist/releases/download/sonora/v0.2.0/sonora_0.2.0_Linux_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "sonora"
  desc "Local-first voice, subtitle, and audio workflow CLI"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the verified yeisme-dist catalog."
  end

  binary "sonora"

  # No zap stanza required
end
