#!/usr/bin/env bash
# Generate public Homebrew and Scoop manifests from the already-mirrored
# yeisme-dist catalog. This script never reads private product repositories.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$ROOT/catalog.json"
OUTPUT_ROOT="$ROOT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --catalog) CATALOG="$2"; shift 2 ;;
    --output-root) OUTPUT_ROOT="$2"; shift 2 ;;
    *) printf 'unknown flag: %s\n' "$1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null || { echo 'jq required' >&2; exit 2; }
[[ -f "$CATALOG" ]] || { echo "catalog not found: $CATALOG" >&2; exit 2; }

mkdir -p "$OUTPUT_ROOT/Casks" "$OUTPUT_ROOT/bucket"

load_release() {
  product="$1"
  tag="$(jq -er --arg product "$product" '
    .products[] | select(.name == $product) | .latest | select(type == "string")
  ' "$CATALOG")"
  version="${tag#"$product"/v}"
  if [[ "$tag" != "$product/v$version" || ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "unsupported $product latest tag: $tag" >&2
    exit 1
  fi

  release_json="$(jq -ce --arg product "$product" --arg tag "$tag" '
    .products[] | select(.name == $product) | .releases[] | select(.tag == $tag)
  ' "$CATALOG")"
  release_version="$(jq -er '.version | select(type == "string")' <<<"$release_json")"
  if [[ "$release_version" != "v$version" ]]; then
    echo "$product release version $release_version does not match latest tag $tag" >&2
    exit 1
  fi
}

digest_for() {
  local name="$1" digest
  digest="$(jq -er --arg name "$name" '.asset_digests[$name] | select(type == "string")' <<<"$release_json")"
  if [[ ! "$digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "missing SHA-256 digest for $name" >&2
    return 1
  fi
  printf '%s\n' "${digest#sha256:}"
}

require_assets() {
  local required_asset
  for required_asset in "$@"; do
    [[ -z "$required_asset" ]] && continue
    if ! jq -e --arg name "$required_asset" '(.assets // []) | index($name) != null' <<<"$release_json" >/dev/null; then
      echo "$product release $tag is missing required asset $required_asset" >&2
      exit 1
    fi
  done
}

write_platform_block() {
  local platform="$1" arm_asset="$2" intel_asset="$3" asset cask_asset sha
  [[ -z "$arm_asset" && -z "$intel_asset" ]] && return
  printf '  on_%s do\n' "$platform"
  for asset in "$arm_asset" "$intel_asset"; do
    [[ -z "$asset" ]] && continue
    sha="$(digest_for "$asset")"
    if [[ "$asset" == "$arm_asset" ]]; then
      printf '    on_arm do\n'
    else
      printf '    on_intel do\n'
    fi
    printf '      sha256 "%s"\n' "$sha"
    cask_asset="${asset//$version/'#{version}'}"
    printf '      url "https://github.com/yeisme/yeisme-dist/releases/download/%s/v#{version}/%s",\n' "$product" "$cask_asset"
    printf '          verified: "github.com/yeisme/yeisme-dist/"\n'
    printf '    end\n'
  done
  printf '  end\n'
}

write_cask() {
  local description="$1" binary="$2" darwin_amd64="$3" darwin_arm64="$4"
  local linux_amd64="$5" linux_arm64="$6" caveat="$7" cask_tmp
  require_assets "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"
  cask_tmp="$(mktemp)"
  {
    printf '# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.\n'
    printf 'cask "%s" do\n' "$product"
    printf '  version "%s"\n\n' "$version"
    write_platform_block macos "$darwin_arm64" "$darwin_amd64"
    [[ -n "$darwin_amd64$darwin_arm64" ]] && printf '\n'
    write_platform_block linux "$linux_arm64" "$linux_amd64"
    printf '\n  name "%s"\n' "$product"
    printf '  desc "%s"\n' "$description"
    printf '  homepage "https://github.com/yeisme/yeisme-dist"\n\n'
    printf '  livecheck do\n'
    printf '    skip "Generated from the yeisme-dist catalog."\n'
    printf '  end\n\n'
    printf '  binary "%s"\n' "$binary"
    if [[ -n "$caveat" ]]; then
      printf '\n  caveats <<~EOS\n%s\n  EOS\n' "$caveat"
    fi
    printf '\n  # No zap stanza required\nend\n'
  } > "$cask_tmp"
  mv "$cask_tmp" "$OUTPUT_ROOT/Casks/$product.rb"
  echo "generated $OUTPUT_ROOT/Casks/$product.rb"
}

write_scoop() {
  local description="$1" license="$2" binary="$3" windows_amd64="$4"
  local windows_arm64="$5" note="$6" amd64_sha="" arm64_sha="" bucket_tmp
  [[ -z "$windows_amd64" && -z "$windows_arm64" ]] && return
  require_assets "$windows_amd64" "$windows_arm64"
  [[ -n "$windows_amd64" ]] && amd64_sha="$(digest_for "$windows_amd64")"
  [[ -n "$windows_arm64" ]] && arm64_sha="$(digest_for "$windows_arm64")"
  bucket_tmp="$(mktemp)"
  jq -n \
    --arg version "$version" \
    --arg description "$description." \
    --arg homepage "https://github.com/yeisme/yeisme-dist" \
    --arg license "$license" \
    --arg base "https://github.com/yeisme/yeisme-dist/releases/download/$tag" \
    --arg amd64_asset "$windows_amd64" \
    --arg amd64_sha "$amd64_sha" \
    --arg arm64_asset "$windows_arm64" \
    --arg arm64_sha "$arm64_sha" \
    --arg binary "$binary.exe" \
    --arg note "$note" '
    {
      version: $version,
      description: $description,
      homepage: $homepage,
      license: $license,
      architecture: (
        {}
        + (if $amd64_asset == "" then {} else {
            "64bit": {url: ($base + "/" + $amd64_asset), hash: $amd64_sha}
          } end)
        + (if $arm64_asset == "" then {} else {
            arm64: {url: ($base + "/" + $arm64_asset), hash: $arm64_sha}
          } end)
      ),
      bin: $binary
    } + (if $note == "" then {} else {notes: ($note | split("\n") | map(select(length > 0)))} end)
  ' > "$bucket_tmp"
  mv "$bucket_tmp" "$OUTPUT_ROOT/bucket/$product.json"
  echo "generated $OUTPUT_ROOT/bucket/$product.json"
}

generate_product() {
  local requested_product="$1" description="$2" license="$3" binary="$4"
  local darwin_amd64="$5" darwin_arm64="$6" linux_amd64="$7" linux_arm64="$8"
  local windows_amd64="$9" windows_arm64="${10}" caveat="${11}" note="${12}"
  load_release "$requested_product"
  darwin_amd64="${darwin_amd64//@VERSION@/$version}"
  darwin_arm64="${darwin_arm64//@VERSION@/$version}"
  linux_amd64="${linux_amd64//@VERSION@/$version}"
  linux_arm64="${linux_arm64//@VERSION@/$version}"
  windows_amd64="${windows_amd64//@VERSION@/$version}"
  windows_arm64="${windows_arm64//@VERSION@/$version}"
  write_cask "$description" "$binary" "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64" "$caveat"
  write_scoop "$description" "$license" "$binary" "$windows_amd64" "$windows_arm64" "$note"
}

load_release eikona
require_assets \
  checksums.txt \
  eikona-install-manifest.json \
  "eikona-command-catalog_${version}.json" \
  "eikona-skills_${version}.json" \
  "eikona-skills_${version}.tar.gz"
write_cask \
  "Agent-first visual asset runtime and image-generation CLI" eikona \
  "eikona_${version}_Darwin_x86_64.tar.gz" "eikona_${version}_Darwin_arm64.tar.gz" \
  "eikona_${version}_Linux_x86_64.tar.gz" "eikona_${version}_Linux_arm64.tar.gz" \
  $'    Preview local configuration and exact-version Agent Skills setup:\n      eikona setup\n    Apply the reviewed local setup:\n      eikona setup --yes'
write_scoop \
  "Agent-first visual asset runtime and image-generation CLI" MIT eikona \
  "eikona_${version}_Windows_x86_64.zip" "eikona_${version}_Windows_arm64.zip" \
  $'Preview local configuration and exact-version Agent Skills setup: eikona setup\nApply the reviewed local setup: eikona setup --yes'

generate_product pinax \
  "Local-first Markdown knowledge workspace CLI" MIT pinax \
  "pinax_@VERSION@_darwin_x86_64.tar.gz" "pinax_@VERSION@_darwin_aarch64.tar.gz" \
  "pinax_@VERSION@_linux_x86_64.tar.gz" "pinax_@VERSION@_linux_aarch64.tar.gz" \
  "pinax_@VERSION@_windows_x86_64.zip" "pinax_@VERSION@_windows_aarch64.zip" "" ""

generate_product auctra \
  "Local-first writing and story development CLI" Proprietary auctra \
  "auctra_@VERSION@_darwin_amd64.tar.gz" "auctra_@VERSION@_darwin_arm64.tar.gz" \
  "auctra_@VERSION@_linux_amd64.tar.gz" "auctra_@VERSION@_linux_arm64.tar.gz" \
  "auctra_@VERSION@_windows_amd64.zip" "auctra_@VERSION@_windows_arm64.zip" "" ""

generate_product scaena \
  "CLI and agent runtime for AI drama production workflows" Proprietary scaena \
  "" "" "scaena_linux_amd64.tar.gz" "" "" "" "" ""

generate_product gitea-mcp \
  "Gitea MCP server for repository automation" MIT gitea-mcp \
  "gitea-mcp_Darwin_x86_64.tar.gz" "gitea-mcp_Darwin_arm64.tar.gz" \
  "gitea-mcp_Linux_x86_64.tar.gz" "gitea-mcp_Linux_arm64.tar.gz" \
  "gitea-mcp_Windows_x86_64.zip" "gitea-mcp_Windows_arm64.zip" "" ""

generate_product sonora \
  "Local-first voice, subtitle, and audio workflow CLI" Proprietary sonora \
  "sonora_@VERSION@_Darwin_x86_64.tar.gz" "sonora_@VERSION@_Darwin_arm64.tar.gz" \
  "sonora_@VERSION@_Linux_x86_64.tar.gz" "sonora_@VERSION@_Linux_arm64.tar.gz" \
  "sonora_@VERSION@_Windows_x86_64.zip" "sonora_@VERSION@_Windows_arm64.zip" "" ""

generate_product anatomia \
  "Authorized video analysis and evidence workflow CLI" Proprietary anatomia \
  "anatomia_@VERSION@_Darwin_x86_64.tar.gz" "anatomia_@VERSION@_Darwin_arm64.tar.gz" \
  "anatomia_@VERSION@_Linux_x86_64.tar.gz" "anatomia_@VERSION@_Linux_arm64.tar.gz" \
  "" "" "" ""

generate_product credentialctl \
  "Local shared credential and project-secret CLI" Proprietary credentialctl \
  "credentialctl_@VERSION@_darwin_x86_64.tar.gz" "credentialctl_@VERSION@_darwin_aarch64.tar.gz" \
  "credentialctl_@VERSION@_linux_x86_64.tar.gz" "credentialctl_@VERSION@_linux_aarch64.tar.gz" \
  "credentialctl_@VERSION@_windows_x86_64.zip" "" \
  $'    Install or update the credentialctl Agent Skill:\n      npx --yes skills add https://github.com/yeisme/yeisme-agent-my-skills --skill credentialctl-usage --yes' \
  "Install the Agent Skill with: npx --yes skills add https://github.com/yeisme/yeisme-agent-my-skills --skill credentialctl-usage --yes"
