#!/usr/bin/env bash
# Generate public Homebrew and Scoop manifests from the already-mirrored
# yeisme-dist catalog. This script never reads private product repositories.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$ROOT/catalog.json"
OUTPUT_ROOT="$ROOT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --catalog) CATALOG="$2"; shift 2 ;;
    --output-root) OUTPUT_ROOT="$2"; shift 2 ;;
    *) printf 'unknown flag: %s\n' "$1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null || { echo 'jq required' >&2; exit 2; }
[[ -f "$CATALOG" ]] || { echo "catalog not found: $CATALOG" >&2; exit 2; }

product="eikona"
tag="$(jq -er --arg product "$product" '
  .products[] | select(.name == $product) | .latest | select(type == "string")
' "$CATALOG")"
version="${tag#eikona/v}"
if [[ "$tag" != "eikona/v$version" || ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "unsupported eikona latest tag: $tag" >&2
  exit 1
fi

release_json="$(jq -ce --arg product "$product" --arg tag "$tag" '
  .products[] | select(.name == $product) | .releases[] | select(.tag == $tag)
' "$CATALOG")"
release_version="$(jq -er '.version | select(type == "string")' <<<"$release_json")"
if [[ "$release_version" != "v$version" ]]; then
  echo "eikona release version $release_version does not match latest tag $tag" >&2
  exit 1
fi

digest_for() {
  local name="$1" digest
  digest="$(jq -er --arg name "$name" '.asset_digests[$name] | select(type == "string")' <<<"$release_json")"
  if [[ ! "$digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "missing SHA-256 digest for $name" >&2
    return 1
  fi
  printf '%s\n' "${digest#sha256:}"
}

darwin_amd64="eikona_${version}_Darwin_x86_64.tar.gz"
darwin_arm64="eikona_${version}_Darwin_arm64.tar.gz"
linux_amd64="eikona_${version}_Linux_x86_64.tar.gz"
linux_arm64="eikona_${version}_Linux_arm64.tar.gz"
windows_amd64="eikona_${version}_Windows_x86_64.zip"
windows_arm64="eikona_${version}_Windows_arm64.zip"

required_assets=(
  "checksums.txt"
  "eikona-install-manifest.json"
  "eikona-command-catalog_${version}.json"
  "eikona-skills_${version}.json"
  "eikona-skills_${version}.tar.gz"
  "$darwin_amd64"
  "$darwin_arm64"
  "$linux_amd64"
  "$linux_arm64"
  "$windows_amd64"
  "$windows_arm64"
)
for required_asset in "${required_assets[@]}"; do
  if ! jq -e --arg name "$required_asset" '(.assets // []) | index($name) != null' <<<"$release_json" >/dev/null; then
    echo "eikona release $tag is missing required asset $required_asset" >&2
    exit 1
  fi
done

darwin_amd64_sha="$(digest_for "$darwin_amd64")"
darwin_arm64_sha="$(digest_for "$darwin_arm64")"
linux_amd64_sha="$(digest_for "$linux_amd64")"
linux_arm64_sha="$(digest_for "$linux_arm64")"
windows_amd64_sha="$(digest_for "$windows_amd64")"
windows_arm64_sha="$(digest_for "$windows_arm64")"

mkdir -p "$OUTPUT_ROOT/Casks" "$OUTPUT_ROOT/bucket"
cask_tmp="$(mktemp)"
bucket_tmp="$(mktemp)"
trap 'rm -f "$cask_tmp" "$bucket_tmp"' EXIT

cat > "$cask_tmp" <<EOF
# This file is generated by scripts/generate-package-manifests.sh. DO NOT EDIT.
cask "eikona" do
  version "$version"

  on_macos do
    on_arm do
      sha256 "$darwin_arm64_sha"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Darwin_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "$darwin_amd64_sha"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Darwin_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end
  on_linux do
    on_arm do
      sha256 "$linux_arm64_sha"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Linux_arm64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
    on_intel do
      sha256 "$linux_amd64_sha"
      url "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v#{version}/eikona_#{version}_Linux_x86_64.tar.gz",
          verified: "github.com/yeisme/yeisme-dist/"
    end
  end

  name "eikona"
  desc "Agent-first visual asset runtime and image-generation CLI"
  homepage "https://github.com/yeisme/yeisme-dist"

  livecheck do
    skip "Generated from the verified yeisme-dist catalog."
  end

  binary "eikona"

  caveats <<~EOS
    Preview local configuration and exact-version Agent Skills setup:
      eikona setup
    Apply the reviewed local setup:
      eikona setup --yes
  EOS

  # No zap stanza required
end
EOF

jq -n \
  --arg version "$version" \
  --arg base "https://github.com/yeisme/yeisme-dist/releases/download/eikona/v$version" \
  --arg amd64_asset "$windows_amd64" \
  --arg amd64_sha "$windows_amd64_sha" \
  --arg arm64_asset "$windows_arm64" \
  --arg arm64_sha "$windows_arm64_sha" '
  {
    version: $version,
    description: "Agent-first visual asset runtime and image-generation CLI.",
    homepage: "https://github.com/yeisme/yeisme-dist",
    license: "MIT",
    architecture: {
      "64bit": {
        url: ($base + "/" + $amd64_asset),
        hash: $amd64_sha
      },
      arm64: {
        url: ($base + "/" + $arm64_asset),
        hash: $arm64_sha
      }
    },
    bin: "eikona.exe",
    notes: [
      "Preview local configuration and exact-version Agent Skills setup: eikona setup",
      "Apply the reviewed local setup: eikona setup --yes"
    ]
  }
' > "$bucket_tmp"

mv "$cask_tmp" "$OUTPUT_ROOT/Casks/eikona.rb"
mv "$bucket_tmp" "$OUTPUT_ROOT/bucket/eikona.json"
trap - EXIT
echo "generated $OUTPUT_ROOT/Casks/eikona.rb"
echo "generated $OUTPUT_ROOT/bucket/eikona.json"
